# baseURL: https://fridaypodcastclub.com/
# TODO convert to TOML?
baseURL: /
languageCode: en-us
title: Friday Podcast Club
enableEmoji: true
# For html in markdown.
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  tag: tags
  podcast: podcasts
buildFuture: true
